### ISSUE TITLE
Stopped on "TriggerOpeningCutscene"

### ISSUE THREAD

**Issue by Turgonn** [jammsen/docker-sons-of-the-forest-dedicated-server#12]
Hello when running the bash it ends stopping on this line "TriggerOpeningCutscene" do you know what could be the source of that issue ?
My VPS is on ubuntu 20.04

**Comment by jammsen** [comment]
Need a log or screenshots and ANY sort of usefull system data, except Ubuntu to help you out. Dont forget Hardware Specs.

**Comment by ljismail0** [comment]
Hello, I am trying to get this running on my system and I ran into the same issue. The logs just end at `TriggerOpeningCutscene` and the server is not discoverable as far as I can tell.  Any ideas on the best way to troubleshoot this? 

I have attached the log for reference.

I am running on the container on my TrueNas Scale 22.12.3.1 (debian) instance with portainer (I have other containers running this way without any issues). 

Specs:
AMD Ryzen 7 3700X
Nvidia GTX 1660
64GB Memory

[_sonsOfTheForest_logs.txt](https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/files/12010177/_sonsOfTheForest_logs.txt)

**Comment by jammsen** [comment]
Hey @ljismail0 i would hoped you would have created your own issue for this problem, because i cant be sure if your problem is the same as @Turgonn who didnt provide any information yet. 

Now i have to mix answers at target-audiences with maybe different problems, which splits context and focus.

Long-Story short, your log looks good to me, you should be able to play, the log even reads that its loading an existing savegame. I dont see any problems with the logs and when i tested this, my log looked similar and it just worked for me. You sure you dont have a connection problem like in #5 ?

**Comment by jammsen** [comment]
@Turgonn please provide information to help you or i will inactivity close this issue. Thanks.

**Comment by ljismail0** [comment]
> 

Appologies, I thought it might be helpful in the same issue. I will review the other issues and create a new issue if needed. Thanks.

**Comment by jammsen** [comment]
@ljismail0 i didnt mean it that harsh, dont want to be rude okay? You want to help in the most effective way without email spamming others you know?

**Comment by jammsen** [comment]
Closed because of inactivity
