### ISSUE TITLE
Server marked as "invalid" in server list

### ISSUE THREAD

**Issue by mbtronics** [jammsen/docker-sons-of-the-forest-dedicated-server#19]
First of all, many thanks for putting this in a docker container!

I got everything running, the server starts and all looks good.
But when I try to join the server it is not listed under it's name in the list with dedicated servers, I can see the server however with it's IP and port, marked as "invalid".

No idea why, the server config looks fine, no errors.
Checked the UDP ports with nmap, looks fine.
Both server and client run latest version of the game.

I'm running the docker image as regular user on ubuntu, my steam client is on linux (I can connect to other servers just fine).
If there are any logs I can provide just let me know.

**Comment by jammsen** [comment]
Hey @mbtronics 

> First of all, many thanks for putting this in a docker container!

No Problem!

Soooo .... I took the time to create a "Bug-Report" template where i ask and explain certain things from/for you.
You can find it here: https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/issues/new/choose
Please review this and maybe re-created this issue and understand where i can be of help and where not, at the moment im not so sure on how to help you, im missing context, informations, screenshots, logs and other useful infos on how to break/narrow-down and visualize your problem, because i seem to never had this one.

**Comment by mbtronics** [comment]
Ok, I'll write a detailed report later today or tomorrow.

thanks


In short: I'm looking for information about the server being marked as
"invalid", but can't find anything with regular google searches.

**Comment by mbtronics** [comment]
see #22

**Comment by jammsen** [comment]
Closing this in favor of #22 for you.
