### ISSUE TITLE
Server marked as "invalid" in dedicated server list

### ISSUE THREAD

**Issue by mbtronics** [jammsen/docker-sons-of-the-forest-dedicated-server#22]
**Describe the bug**
After setting up the docker container and opening all ports on the firewall, the server is visible but marked as "invalid" in the list with dedicated servers in the game.

**To Reproduce**
- copy the docker-compose.yml file
- create the two directories
- open the three UDP ports in the firewall
- start the container with docker-compose
- stop the container and update the dedicatedserver.cfg file in the game/userdata dir
- start the container => everything starts without errors
- go to the dedicated server list in the game
- server IP is visible but marked as invalid

**Expected behavior**
Server is accessible and not marked as invalid

**Screenshots**
![screenshot](https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/assets/456188/1654a1cd-78e7-46d7-943f-3489eeef3c68)

**Software (please complete the following information):**
 - OS: Ubuntu 21.04
 - Docker: 20.10.8, build 3967b7d

**Hardware (please complete the following information):**
 - vCPU: Intel(R) Xeon(R) CPU E3-1245 V2 @ 3.40GHz
 - RAM: 32GB
 - Disk: 1TB SSD

**Additional context**
- firewall: ufw, but also tried it with firewall fully disabled
- running steam on linux on client side
- full docker log:  
[sotf_docker_log.txt](https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/files/12110474/sotf_docker_log.txt)

**Comment by mbtronics** [comment]
I just tried it on a different server, and it just works.
Exact same setup, server on the same network.
Except this one has more recent software:

Docker version 20.10.17, build 100c701
Ubuntu 22.04.1 LTS

I will try to make a detailed comparison between the docker container logs when I have more time.

**Comment by jammsen** [comment]
Hey @mbtronics 
i was busy this week sorry for no response on this.
Very good first issue, love it!

This weird behvaior is honestly the first time i encounter something like this, i never had this once in all of my testing in Sons or TheForest before. But yes now that you mention it, i can actively look for it its weird.

From my understanding your gameserver registers at the master-server at startup and you get "listed" in "THE LIST" basically the single source of truth that every player get when you see ingame the "refresh" of gameserver, you get a list and the server get parsed/contacted/infos-get-transfered one of thoose it has to be, be honestly is a black-box for me i didnt programm it and the devs dont tell you.

When everything goes well it looks like this:
![image](https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/assets/2270806/16d5ea02-8856-488d-b666-d280046426a3)

If it doesnt (i guess) it looks like this? (again guessing):
![image](https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/assets/2270806/67592c36-af16-4ca0-b785-5b20c388eae0)

To be honest i was VERY surprised you actually got to see IP:PORTs i never had that, but now it makes more sense.

Not sure how my docker-interactions might cause this, because i dont see anything wrong with your log, even the network/port/IP self-test "just run" successful. 

@ich777 Did you run into anything similar with your version on Unraid?

**Comment by jammsen** [comment]
> I just tried it on a different server, and it just works. Exact same setup, server on the same network. Except this one has more recent software:
> 
> Docker version 20.10.17, build 100c701 Ubuntu 22.04.1 LTS
> 
> I will try to make a detailed comparison between the docker container logs when I have more time.

If you find something please provide any input, might be of help for others and important to post the solution here.

**Comment by jammsen** [comment]
Ive talked to @ich777 how does a similar image then i do, hes awesome.

He said, he never had this happen for him and i might be down to out-dated version, wrong config or and outdated config.

Maybe that helps to make the comparsion smaller.

**Comment by jammsen** [comment]
@mbtronics Any updates on this? Can this be closed?

**Comment by jammsen** [comment]
Closed because of inactivity

**Comment by mbtronics** [comment]
Meanwhile, I can confirm the older version of docker is to blame, but no idea why.
It works perfectly with a newer version.
