### ISSUE TITLE
Performance under Wine

### ISSUE THREAD

**Issue by JS-E** [jammsen/docker-sons-of-the-forest-dedicated-server#7]
Hi there,

This is really cool stuff so first off good job! 👍 

Just wondering if you've done any performance testing under wine vs dedicated windows setup? It's a shame SOTF doesn't support linux at the moment as i can imagine it would be much easier to get running under linux.

**Comment by jammsen** [comment]
I did test it on my root and local on my NAS in VMs and Docker-Container (Linux and Windows alike) and the performance was for me identical. (I mean Wine is just a compability layer for Linux and Windows, dunno about performance impacts)

**Comment by JS-E** [comment]
So according to my research it does depend on the game, some games (like borderland) have quite a significant drop in performance under wine, but if you have tested it then it should be good. Also i assume that because this is just doing pure hosting calculations and not rendering anything it'll be less problematic 👍

**Comment by jammsen** [comment]
Yeah its not like its rendering something and you actually play this as a game, its only a handler for a game-instance with server-fps based on objects and data to stream to players. Its only cpu-based tasks, so i would not worry about that.

**Comment by asarkar157** [comment]
@jammsen  do you have any CPU/RAM sizing recommendations for VMs to host this on?

**Comment by jammsen** [comment]
Hey @asarkar157 
Hmmm i did answer things to my Test-Setup in #4 but thats more "barely minimal" i guess you could say.
> My Docker-Test-Node is 12vCPUs and 8GB RAM, it works fine for testing. If you play with more people i would bump memory more up. 

Afaik there are no official "Minimum System Requirements" for the DS:

My NAS has a "AMD Ryzen™ 7 5700G" 3,8 Base 4,6 Boost

CPU: At least 4 real cores or 6-8 vCPUs if you work with virtualization
RAM: TL;DR ~8-12+GB
Background: 
* For testing 6GB RAM worked fine
* For real hosting and playing i would go for at least 8GB with like 1-3 players and for every additional player i would bump up RAM by about 1GB RAM like 7dtd recommends
* Thats because in the early game you might dont need it, but later with more structures, progress, more items and stuff the "variances" in the map and server (something cut down, something broken, something growing and stuff) and complexity adds up and has to be stored in RAM. 
* I dont have a longer term test with like 8+ players at 80 hours of playing, so i can only assume the growth, but its better to go with the 7dtd recommendations and be wildly over and adjust later, than loose days of progress because the server crashed of RAM problems and the savegame is corrupted.

**Comment by JS-E** [comment]
@jammsen Yeah i did have some more questions, but i think it would be irrelevant for this issue :) Appreciate the response

**Comment by jammsen** [comment]
@JS-E ask them here or make a new issue, just like you feel.

**Comment by asarkar157** [comment]
Just ran into performance issues with 3 players when we started doing very light base building -- tree fall and bird animations were stuttering+slow, then eventually the server host crashed. This was on an Ubuntu VM with 2vCPU+8GB RAM. CPU util was  steady at 80%, but spiked to 90% right before crash, and RAM was consistently at 95% utilized.

I will try again with a 4vCPU+16GB RAM setup and report back

**Comment by jammsen** [comment]
@asarkar157 - lol @ 2vCPUs did you even read my recommendations?
https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/issues/7#issuecomment-1611097781

**Comment by asarkar157** [comment]
Of course! Just reporting back actual test data. I migrated the instance to
4vCPU/16GB RAM and have had no issues so far. If I hit another crash with
this setup, I'll report back and scale up the instance once more :)
